// Code generated by "stringer --type MinNodesAction lbpool/minnodesaction.go"; DO NOT EDIT

package lbpool

import "fmt"

const _MinNodesAction_name = "ForceUpForceDownBackupPool"

var _MinNodesAction_index = [...]uint8{0, 7, 16, 26}

func (i MinNodesAction) String() string {
	if i < 0 || i >= MinNodesAction(len(_MinNodesAction_index)-1) {
		return fmt.Sprintf("MinNodesAction(%d)", i)
	}
	return _MinNodesAction_name[_MinNodesAction_index[i]:_MinNodesAction_index[i+1]]
}
