// Code generated by "stringer --type HCResult healthcheck/result.go"; DO NOT EDIT

package healthcheck

import "fmt"

const _HCResult_name = "HCUnknownHCErrorHCBadHCGood"

var _HCResult_index = [...]uint8{0, 9, 16, 21, 27}

func (i HCResult) String() string {
	if i < 0 || i >= HCResult(len(_HCResult_index)-1) {
		return fmt.Sprintf("HCResult(%d)", i)
	}
	return _HCResult_name[_HCResult_index[i]:_HCResult_index[i+1]]
}
